<a href="https://colab.research.google.com/github/Lahari-1402/Hotel_Tips-using-DeepLearning/blob/main/dl_hoteltips.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset('tips')

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [ ]:
dictionary1 = {'Female':0, 'Male':1}
df['sex'] = df['sex'].map(dictionary1)
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,0,No,Sun,Dinner,2
1,10.34,1.66,1,No,Sun,Dinner,3
2,21.01,3.50,1,No,Sun,Dinner,3
3,23.68,3.31,1,No,Sun,Dinner,2
4,24.59,3.61,0,No,Sun,Dinner,4


In [ ]:
df['smoker'].unique()

['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [ ]:
dictionary2 = {'No':0, 'Yes':1}
df['smoker'] = df['smoker'].map(dictionary2)
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,0,0,Sun,Dinner,2
1,10.34,1.66,1,0,Sun,Dinner,3
2,21.01,3.50,1,0,Sun,Dinner,3
3,23.68,3.31,1,0,Sun,Dinner,2
4,24.59,3.61,0,0,Sun,Dinner,4


In [ ]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [ ]:
dictionary3 = {'Sun':1, 'Sat':2,'Thur':3,'Fri':4}
df['day'] = df['day'].map(dictionary3)
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,0,0,1,Dinner,2
1,10.34,1.66,1,0,1,Dinner,3
2,21.01,3.50,1,0,1,Dinner,3
3,23.68,3.31,1,0,1,Dinner,2
4,24.59,3.61,0,0,1,Dinner,4


In [ ]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [ ]:
dictionary4 = {'Dinner':0, 'Lunch':1}
df['time'] = df['time'].map(dictionary4)
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,0,0,1,0,2
1,10.34,1.66,1,0,1,0,3
2,21.01,3.50,1,0,1,0,3
3,23.68,3.31,1,0,1,0,2
4,24.59,3.61,0,0,1,0,4


In [ ]:
x = df.drop('tip', axis=1)
y = df['tip']

In [ ]:
import tensorflow as tf
#step 1 : create neuron layers with neurons
layer1 = tf.keras.layers.Dense(units=4, input_dim = 6)
layer2 = tf.keras.layers.Dense(units=32)
layer3 = tf.keras.layers.Dense(units=32)
layer4 = tf.keras.layers.Dense(units=64)
layer5 = tf.keras.layers.Dense(units=64)
layer6 = tf.keras.layers.Dense(units=128)
layer7 = tf.keras.layers.Dense(units=64)
layer8 = tf.keras.layers.Dense(units=64)
layer9 = tf.keras.layers.Dense(units=1)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
#Step 2 : add all layers to model
model = tf.keras.models.Sequential()
model.add(layer1)
model.add(layer2)
model.add(layer3)
model.add(layer4)
model.add(layer5)
model.add(layer6)
model.add(layer7)
model.add(layer8)
model.add(layer9)

In [ ]:
#Step 3 : give optimizer, loss and metrics
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mean_squared_error'])

In [ ]:
model.fit(x,y,epochs=50)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1301 - mean_squared_error: 1.1301 
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1246 - mean_squared_error: 1.1246 
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1322 - mean_squared_error: 1.1322 
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0970 - mean_squared_error: 1.0970 
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1321 - mean_squared_error: 1.1321 
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0980 - mean_squared_error: 1.0980 
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0968 - mean_squared_error: 1.0968 
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0904 - mean_squared_error: 1.0904 
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0799 - mean_squared_error: 1.0799 
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0872 - mean_squared_error: 1.0872 
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0804 - me

In [ ]:
import numpy as np
model.predict(np.array([[21.01,1,0,1,0,3]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step


array([[3.300546]], dtype=float32)

In [ ]:
model.predict(np.array([[24.59,0,0,1,0,4]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[3.6287801]], dtype=float32)

In [ ]:
model.predict(np.array([[16.99,0,0,1,0,2]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[2.58721]], dtype=float32)